version: '3'

services:
  redis:
    image: redis:6
    container_name: redis-service
    restart: always
    ports:
      - '6379:6379'

  publisher:
    build: publisher
    container_name: "publisher"
    depends_on:
      - redis
    ports:
      - '8080:8080'

  subscriber-1:
    build: subscriber
    container_name: "subscriber-1"
    depends_on:
      - redis
    ports:
      - '8081:8080'

  subscriber-2:
    build: subscriber
    container_name: "subscriber-2"
    depends_on:
      - redis
    ports:
      - '8082:8080'
